version: '3.8'

services:
  frontend:
    image: public.ecr.aws/c3q9m2e4/techverito_frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
    depends_on:
      - backend  

  db:
    image: postgres
    container_name: my-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  
      interval: 5s
      retries: 5
      start_period: 10s

  backend:
    image: public.ecr.aws/c3q9m2e4/techverito_backend:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    depends_on:
      db:
        condition: service_healthy  
