name: Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # Update path to match your frontend directory structure
      - 'backend/**'  # Update path to match your backend directory structure

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: your-aws-region # Replace with your AWS region
          AWS_ACCOUNT_ID: your-aws-account-id # Replace with your AWS account ID

      - name: Build and Push Frontend Image
        working-directory: frontend # Update to match your frontend directory name
        run: |
          ls -ltr  # For debugging purposes
          docker build -t your-frontend-image-name .
          docker tag your-frontend-image-name ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/your-frontend-image-name:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/your-frontend-image-name:latest

      - name: Build and Push Backend Image
        working-directory: backend # Update to match your backend directory name
        run: |
          docker build -t your-backend-image-name .
          docker tag your-backend-image-name ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/your-backend-image-name:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/your-backend-image-name:latest
