name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Login to Amazon ECR
      #   run: |
      #     aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c3q9m2e4
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: us-east-1
      #     AWS_ACCOUNT_ID: c3q9m2e4

      # - name: Build and Push Frontend Image
      #   working-directory: frontend
      #   run: |
      #     docker build -t techverito_frontend:latest .
      #     docker tag techverito_frontend:latest public.ecr.aws/c3q9m2e4/techverito_frontend:latest
      #     docker push public.ecr.aws/c3q9m2e4/techverito_frontend:latest

      # - name: Build and Push Backend Image
      #   working-directory: backend
      #   run: |
      #     docker build -t techverito_backend:latest .
      #     docker tag techverito_backend:latest public.ecr.aws/c3q9m2e4/techverito_backend:latest
      #     docker push public.ecr.aws/c3q9m2e4/techverito_backend:latest


      - name: Update Repository
        run: |
          git pull origin main
          ls -ltr 
          pwd

          
      - name: Copy Docker Compose Files to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.242.43.170
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/ec2-user/docker-compose.yml"

      - name: SSH into EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: 54.242.43.170
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/
            docker-compose up -d


      # - name: Start Docker Compose
      #   run: |
      #     cd /path/to/your/docker-compose-directory
      #     docker-compose up -d
