name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c3q9m2e4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          AWS_ACCOUNT_ID: c3q9m2e4

      - name: Build and Push Frontend Image
        working-directory: frontend
        run: |
          docker build -t your-frontend-image-name:latest .
          docker tag your-frontend-image-name:latest public.ecr.aws/c3q9m2e4/your-frontend-image-name:latest
          docker push public.ecr.aws/c3q9m2e4/your-frontend-image-name:latest

      - name: Build and Push Backend Image
        working-directory: backend
        run: |
          docker build -t your-backend-image-name:latest .
          docker tag your-backend-image-name:latest public.ecr.aws/c3q9m2e4/your-backend-image-name:latest
          docker push public.ecr.aws/c3q9m2e4/your-backend-image-name:latest
