name: Build Frontend

on:
  push:
    branches:
      - main
    paths:
      - frontend 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd frontend
          docker build -t frontend:latest .

#      - name: Log in to Docker Hub (or your Docker registry)
#        if: success()
#        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
#
#      - name: Push Docker image
#        if: success()
#        run: docker push your-docker-image-name:latest
