name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
    
      - name: Terraform Init
        run: |
          cd terraform/aws
          terraform init
      
      - name: Terraform Validate
        run: |
          cd terraform/aws
          terraform validate

      - name: Terraform Plan
        run: |
          cd terraform/aws
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd terraform/aws
          terraform apply -auto-approve tfplan
